M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2025-12-13T19:22:32+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-13T19:22:32+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X-12.895Y2.89
X-12.895Y-2.89
M30
